### PR TITLE
Rely on Puppet 7 built-in windows utils

### LINKED ISSUE #51: The agent does not work on windows with Puppet 7
When running on windows nodes with Puppet 7, the module does not work:

```sh-session
romain@optiplex-3050 ~ % mco puppet status -F kernel=windows       

 * [ ============================================================> ] 4 / 4

   desktop-bpi073d.lan: uninitialized constant Win32::Service
   desktop-6qthe1j.lan: uninitialized constant Win32::Service
   desktop-ckj2fkk.lan: uninitialized constant Win32::Service
   desktop-rikk10l.lan: uninitialized constant Win32::Service

Summary of Applying:

   false = 4

Summary of Daemon Running:

   stopped = 4

Summary of Enabled:

     No aggregate summary could be computed

Summary of Idling:

   false = 4

Summary of Status:

   unknown = 4


Finished processing 4 / 4 hosts in 7479.12 ms
```

Puppet 6 shipped with 2 gems which are not bundled anymore with Puppet 7 and are used by the module: `win32-process` and `win32-service`.

### PR DESCRIPTION
**Pull request by smortex**
Prior to Puppet 7, the win32-process and win32-servic gems where bundled in the Puppet AIO package for windows, but where removed as Puppet gained support for these features in it's core:

  - https://github.com/puppetlabs/puppet/commit/321f36fac7856fdd8af82f80d236fb2603a825ea
  - https://github.com/puppetlabs/puppet/commit/50a908694916e812e53b5ab5b0a5302ed9ba9811

Update the code to use the new API when available, and fall-back to the previous code.

This unbreaks the module on windows with Puppet 7.

---

<details>
<summary>Initial issue before full re-write</summary>

These gem where previously installed with Puppet, but where removed from Puppet 7 bundle:
https://github.com/puppetlabs/puppet/commit/321f36fac7856fdd8af82f80d236fb2603a825ea
https://github.com/puppetlabs/puppet/commit/50a908694916e812e53b5ab5b0a5302ed9ba9811

Add them as dependencies to the agent to unbreak it on windows.

Fixes #51

Things I am not sure about:
* which version to stick to. I chose to keep the version previously used in Puppet but it might be better to update them?
* this will install the dependencies on all OSes, but it is only useful on windows. Maybe it's worth adding something to avoid installing unneeded dependencies?

</details>

### CODE REVIEW

**Comment by ripienaar** [comment]
So in Puppet are people supposed to install these by hand or did they move to some other solution that these are not needed anymore?

**Comment by smortex** [comment]
It seems it's not needed anymore in core Puppet, and that they implemented the missing bits in Puppet directly:

- https://github.com/puppetlabs/puppet/commit/6c47969cb180ab5e056565854e78a962b43ab82e (win32/service)
- https://github.com/puppetlabs/puppet/commit/1f468fbf52fff8aa9b78fbc9096ee7408003a67c (win32/process)

While walking to $WORK, I was thinking about adding a level in the agents Hiera hierarchy like `os/%{facts.os.family}/puppet_aio/%{facts.mcollective.puppet_major_version}.yaml` which would allow to ship a `data/os/windows/puppet_aio/7.yaml` that list these dependencies only when needed…  I does not look straightforward though.

Maybe using the Puppet 7 API when available and falling back to the older code makes more sense?  What do you think?

**Comment by ripienaar** [comment]
Yeah, it looks reasonably easy to call their code instead of the gem when on P7, bit annoying but I reckon we can adjust this so these dependencies are just not needed anymore in time which would be great.

So we keep it for P6 and call their code in P7, bit complex, if you'd like me to do the work I am happy to, of course you can also give it a go?

File: util/puppet_agent_mgr/mgr_windows.rb [hunk 1]
```diff
@@ -4,17 +4,29 @@ class PuppetAgentMgr
...
-          when "running", "continue pending", "start pending"
-            true
+          if defined?(Puppet::Util::Windows::Service)
+            # Puppet 7 has built-in support for Windows sevices
+            case Puppet::Util::Windows::Service.service_state(@puppet_service)
+            when :SERVICE_RUNNING, :SERVICE_CONTINUE_PENDING, :SERVICE_START_PENDING
+              true
+            else
+              false
+            end
```
Comment (ripienaar) [inline util/puppet_agent_mgr/mgr_windows.rb:15]: change the entire case statement to:

```ruby
[:SERVICE_RUNNING, :SERVICE_CONTINUE_PENDING, :SERVICE_STATE_PENDING].include?(Puppet::Util::Windows::Service.service_state(@puppet_service))
```

Can do the same with the other one just below

**Review by ripienaar — CHANGES_REQUESTED** [review]
looks good, the "right" thing to do is a new manager version or something, but this is fine for now we can later remove the win32 stuff and it will be clear again

File: util/puppet_agent_mgr/mgr_windows.rb (hunk 1 above)
Comment (smortex) [reply util/puppet_agent_mgr/mgr_windows.rb]: Done!

**Comment by smortex** [comment]
I though that it would be possible to use the same code (provided by Puppet) for all platforms, but it seems that Puppet wrappers always wait for a spawned process to terminate so I stuck to the minimal change that fix the issue and allows an easy removal when this can be done.
